# Generated by Django 4.2.17 on 2025-07-27 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_invitation_sent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpPreRegistrationAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=255)),
                ('preview', models.CharField(help_text='Descriptive name for the API key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'DataUP API Key',
                'verbose_name_plural': 'DataUP API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataUpOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataup', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DataUpAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='API key for DataUp integration', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for the API key', max_length=255)),
                ('preview', models.CharField(help_text='Preview of the API key', max_length=255)),
                ('allowed_roles', models.JSONField(default=list, help_text='List of allowed roles for this API key')),
                ('label', models.CharField(blank=True, help_text='Optional label for the API key', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataup.datauporganization')),
            ],
            options={
                'verbose_name': 'DataUP API Key',
                'verbose_name_plural': 'DataUP API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]