# Generated by Django 4.2.23 on 2025-08-06 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataUpPreRegistrationAPIKey',
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataup.datauporganization'),
        ),
    ]