# Generated by Django 4.2.23 on 2025-08-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataup', '0003_dataupuser_dataupapikey_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataupapikey',
            name='default',
            field=models.BooleanField(default=False, help_text='Is this the default API key for the organization/User'),
        ),
    ]