# Generated by Django 4.2.23 on 2025-08-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataup', '0004_dataupapikey_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataupapikey',
            name='default',
            field=models.BooleanField(default=False, help_text='Is this the default API key within its scope?'),
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this key belongs to (leave empty for user-scoped key)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataup.datauporganization'),
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User this key belongs to (leave empty for org-scoped key)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataup.dataupuser'),
        ),
        migrations.AddIndex(
            model_name='dataupapikey',
            index=models.Index(fields=['owner', 'default'], name='dataup_data_owner_i_c28cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupapikey',
            index=models.Index(fields=['organization', 'default'], name='dataup_data_organiz_4dc162_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupapikey',
            index=models.Index(fields=['created_at'], name='dataup_data_created_e60fee_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupapikey',
            index=models.Index(fields=['last_used_at'], name='dataup_data_last_us_bae394_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataupapikey',
            constraint=models.CheckConstraint(check=models.Q(('owner__isnull', False), ('organization__isnull', False), _connector='OR'), name='api_key_owner_or_org_required'),
        ),
        migrations.AddConstraint(
            model_name='dataupapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True), ('owner__isnull', False)), fields=('owner',), name='uniq_default_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='dataupapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True), ('organization__isnull', False), ('owner__isnull', True)), fields=('organization',), name='uniq_default_per_org'),
        ),
    ]