# Generated by Django 4.2.23 on 2025-08-09 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataup', '0005_alter_dataupapikey_default_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dataupapikey',
            name='uniq_default_per_owner',
        ),
        migrations.RemoveConstraint(
            model_name='dataupapikey',
            name='uniq_default_per_org',
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='allowed_roles',
            field=models.JSONField(default=list, help_text='Org roles allowed to use this key (applies to org-owned keys).'),
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='default',
            field=models.BooleanField(default=False, help_text='Mark as the default key within its scope'),
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this key belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataup.datauporganization'),
        ),
        migrations.AlterField(
            model_name='dataupapikey',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User this key belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dataup.dataupuser'),
        ),
        migrations.AddIndex(
            model_name='dataupapikey',
            index=models.Index(fields=['owner', 'organization', 'default'], name='dataup_data_owner_i_6ac137_idx'),
        ),
        migrations.AddIndex(
            model_name='dataupapikey',
            index=models.Index(fields=['owner', 'organization'], name='dataup_data_owner_i_6eac2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='dataupapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True), ('organization__isnull', True), ('owner__isnull', False)), fields=('owner',), name='uniq_default_personal_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='dataupapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True), ('organization__isnull', False), ('owner__isnull', False)), fields=('owner', 'organization'), name='uniq_default_user_org_pair'),
        ),
        migrations.AddConstraint(
            model_name='dataupapikey',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True), ('organization__isnull', False), ('owner__isnull', True)), fields=('organization',), name='uniq_default_org_only'),
        ),
    ]