# Generated by Django 4.2.26 on 2025-11-22 16:36

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataup', '0006_remove_dataupapikey_uniq_default_per_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LensRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_type', models.CharField(choices=[('job_overview', 'JOB_OVERVIEW'), ('data_health', 'DATA_HEALTH'), ('agent_performance', 'AGENT_PERFORMANCE'), ('annotator_performance', 'ANNOTATOR_PERFORMANCE')], max_length=64)),
                ('task_id', models.BigIntegerField(blank=True, null=True)),
                ('job_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
            ],
            options={
                'unique_together': {('job_id', 'row_type')},
            },
        ),
    ]