# Generated by Django 4.2.26 on 2025-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataup', '0007_lensrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensrow',
            name='org_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]